components:
  - name: DetectDino
  - name: SegmentSam

pipeline:
  - detect
  - segment

dataset:
  path: /workspace/ImagenHeap/datasets/fashion_people_detection/images/train

batch_size: 10

component_args:
  detect:
    text_prompt:
      - hair
      - face
      - neck
      - arm
      - hand
      - back
      - leg
      - foot
      - outfit
      - phone
      - hat
      - shoe
    box_threshold: 0.3
    text_threshold: 0.25
    iou_threshold: 0.8
  segment:
    return_tensors: true