# YOLOv8 Training Configuration

# Training Parameters
epochs: 100
batch: 16
imgsz: 640
workers: 8

# Multi-scale training
# Uncomment the following two lines to enable multi-scale training
multi_scale: True

# Optimizer Settings
optimizer: 'auto'
lr0: 0.001
lrf: 0.01
momentum: 0.937
weight_decay: 0.0005

# Warmup Settings
warmup_epochs: 3.0
warmup_momentum: 0.8
warmup_bias_lr: 0.1

# Loss Function Weights
box: 7.5
cls: 0.5
dfl: 1.5
# Uncomment the following if doing pose estimation
# pose: 12.0
# kobj: 2.0

# Augmentation and Preprocessing
close_mosaic: 10
rect: false
cos_lr: true

# Performance Options
amp: true
fraction: 0.005 # set to 1.0
cache: false
deterministic: true

# Regularization
dropout: 0.0
label_smoothing: 0.0  # Added based on available arguments

# Training Behavior
patience: 10
single_cls: false
overlap_mask: true
mask_ratio: 4

# Saving and Logging
save: true
save_period: -1
exist_ok: false
pretrained: true
verbose: true
plots: true

# Validation
val: true

# Reproducibility
seed: 0